### ISSUE TITLE
[US-1] User Story Title

### ISSUE THREAD

**Issue by njayem** [njayem/RoboFriends#1]
# User Story

**As a** *`persona`*, **I want to** *`do something`* **so that I can** *`realize a reward`*.

## Total Story Points
[ ] Points

## Priority Level:
[Urgent / Important / It can wait]

## Risk
[Low / Medium / High]

## Ideal Time
[ ] Hours

## Tasks 
- [ ] https://github.com/njayem/RoboFriends/commit/25a036db201d89741c4f129c8ab9e74cd638400d 
- [ ] Add additional tasks as needed.

## Demo Steps:
1) 
2)
3)
4) Add more steps as needed.

## Unit Tests 
- [ ] Commit #issue-number
- [ ] Link additional commits as needed.

## Customer Sign Off
Please check the release documents for this iteration.
